export const hexColorRegex = /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/;

export const hexColors = [
  "#FF5733",
  "#C70039",
  "#900C3F",
  "#581845",
  "#FF4500",
  "#FF6347",
  "#FF8C00",
  "#FFA500",
  "#FFD700",
  "#DAA520",
  "#B8860B",
  "#8B4513",
  "#A0522D",
  "#CD5C5C",
  "#E9967A",
  "#F08080",
  "#DC143C",
  "#8B0000",
  "#FF1493",
  "#C71585",
  "#DB7093",
  "#FF69B4",
  "#FF00FF",
  "#8A2BE2",
  "#4B0082",
  "#6A5ACD",
  "#483D8B",
  "#7B68EE",
  "#9370DB",
  "#BA55D3",
  "#9932CC",
  "#8B008B",
  "#9400D3",
  "#800080",
  "#6B8E23",
  "#556B2F",
  "#228B22",
  "#008000",
  "#006400",
  "#32CD32",
  "#00FF00",
  "#ADFF2F",
  "#7FFF00",
  "#7CFC00",
  "#00FA9A",
  "#2E8B57",
  "#3CB371",
  "#20B2AA",
  "#008B8B",
  "#008080",
  "#4682B4",
  "#1E90FF",
  "#0000CD",
  "#00008B",
  "#000080",
  "#4169E1",
  "#6495ED",
  "#00BFFF",
  "#5F9EA0",
  "#48D1CC",
  "#40E0D0",
  "#00CED1",
  "#FFD700",
  "#FFA07A",
  "#FF7F50",
  "#FF6347",
  "#FF4500",
  "#D2691E",
  "#A0522D",
  "#8B4513",
  "#CD853F",
  "#DEB887",
  "#F4A460",
  "#DAA520",
];

export const carModels = [
  "Toyota Corolla",
  "Honda Civic",
  "Ford Focus",
  "Chevrolet Cruze",
  "Nissan Sentra",
  "Hyundai Elantra",
  "Kia Forte",
  "Volkswagen Jetta",
  "Subaru Impreza",
  "Mazda3",
  "Toyota Camry",
  "Honda Accord",
  "Nissan Altima",
  "Ford Fusion",
  "Chevrolet Malibu",
  "Hyundai Sonata",
  "Kia K5",
  "Volkswagen Passat",
  "Subaru Legacy",
  "Mazda6",
  "Toyota Yaris",
  "Honda Fit",
  "Nissan Versa",
  "Hyundai Accent",
  "Kia Rio",
  "Ford Fiesta",
  "Chevrolet Spark",
  "Mitsubishi Mirage",
  "Toyota Prius",
  "Hyundai Ioniq",
  "Honda Insight",
  "Kia Niro",
  "Nissan Leaf",
  "Chevrolet Bolt EV",
  "BMW 3 Series",
  "Audi A4",
  "Mercedes-Benz C-Class",
  "Lexus IS",
  "Infiniti Q50",
  "Acura TLX",
  "Volvo S60",
  "Jaguar XE",
  "Cadillac CT4",
  "Genesis G70",
  "Tesla Model 3",
  "Ford Mustang Mach-E",
  "Hyundai Kona",
  "Toyota RAV4",
  "Honda CR-V",
  "Nissan Rogue",
  "Ford Escape",
  "Chevrolet Equinox",
  "Hyundai Tucson",
  "Kia Sportage",
  "Volkswagen Tiguan",
  "Subaru Forester",
  "Mazda CX-5",
  "Toyota Highlander",
  "Honda Pilot",
  "Nissan Pathfinder",
  "Ford Explorer",
  "Chevrolet Traverse",
  "Kia Sorento",
  "Hyundai Santa Fe",
  "Volkswagen Atlas",
  "Subaru Outback",
  "Jeep Cherokee",
  "Jeep Grand Cherokee",
  "Toyota 4Runner",
  "Ford Bronco",
  "Nissan Murano",
  "Honda HR-V",
  "Toyota C-HR",
  "Kia Seltos",
  "Hyundai Palisade",
  "Chevrolet Tahoe",
  "Ford Expedition",
  "GMC Yukon",
  "Nissan Armada",
  "Lexus RX",
  "Lexus NX",
  "Acura RDX",
  "BMW X3",
  "BMW X5",
  "Audi Q5",
  "Audi Q7",
  "Mercedes GLC",
  "Mercedes GLE",
  "Volvo XC60",
  "Volvo XC90",
  "Infiniti QX50",
  "Infiniti QX60",
  "Jaguar F-Pace",
  "Land Rover Discovery Sport",
  "Land Rover Range Rover",
  "Porsche Macan",
  "Porsche Cayenne",
  "Tesla Model Y",
  "Rivian R1S",
  "Chevrolet Blazer",
  "Ford Mustang GT",
  "Chevrolet Camaro SS",
  "Dodge Challenger R/T",
  "Nissan 370Z",
  "Nissan Z",
  "Toyota GR Supra",
  "Toyota 86",
  "Subaru BRZ",
  "Mazda MX-5 Miata",
  "BMW Z4",
  "Audi TT",
  "Porsche 718 Cayman",
  "Porsche 718 Boxster",
  "Jaguar F-Type",
  "Mercedes-AMG SL",
  "Mercedes-AMG GT",
  "Aston Martin Vantage",
  "Lexus RC F",
  "Infiniti Q60",
  "Chevrolet Corvette C8",
  "Dodge Viper",
  "Ford GT",
  "Lotus Evora",
  "Alpine A110",
  "BMW M2",
  "BMW M4",
  "BMW M3",
  "Audi RS5",
  "Audi RS7",
  "Mercedes AMG C63",
  "Ferrari 488",
  "Ferrari F8 Tributo",
  "Ferrari SF90 Stradale",
  "Ferrari Roma",
  "Lamborghini Huracán",
  "Lamborghini Aventador",
  "Lamborghini Revuelto",
  "McLaren 720S",
  "McLaren Artura",
  "McLaren P1",
  "Bugatti Chiron",
  "Bugatti Veyron",
  "Pagani Huayra",
  "Pagani Zonda",
  "Koenigsegg Jesko",
  "Koenigsegg Gemera",
  "Aston Martin DBS Superleggera",
  "Aston Martin Valkyrie",
  "Lotus Emira",
  "Porsche 911 Turbo S",
  "Porsche 911 GT3 RS",
  "Rimac Nevera",
  "Maserati MC20",
  "Maserati Alfieri",
  "Bentley Continental GT Speed",
  "Bentley Mulliner Bacalar",
  "Ferrari 812 Superfast",
  "Lamborghini Sián",
  "Ferrari Daytona SP3",
  "McLaren Elva",
  "Ferrari Monza SP1",
  "Ferrari Monza SP2",
  "Lamborghini Centenario",
  "Lamborghini Murciélago",
  "Lamborghini Gallardo",
  "McLaren Senna",
  "McLaren 600LT",
  "McLaren 765LT",
  "Bugatti Divo",
  "Bugatti Centodieci",
  "Pagani Huayra Roadster",
  "Pagani Zonda R",
  "Koenigsegg Agera RS",
  "Koenigsegg Regera",
  "Aston Martin V12 Vantage",
  "Aston Martin Rapide",
  "Lotus Exige",
  "Lotus Elise",
  "Porsche Taycan",
  "Porsche Panamera",
  "Porsche 911 Carrera S",
  "Porsche 911 GT2 RS",
  "Maserati GranTurismo",
  "Maserati Quattroporte",
  "Bentley Flying Spur",
  "Bentley Bentayga",
  "Audi R8",
  "Audi RS6 Avant",
  "Audi RS Q8",
  "Mercedes AMG GT R",
  "Mercedes AMG One",
  "Mercedes SLS AMG",
  "BMW i8",
  "BMW M8",
  "BMW M6",
  "Lexus LC 500",
  "Lexus LFA",
  "Nissan GT-R",
  "Nissan Skyline GT-R",
  "Toyota Century",
  "Ford Ranger",
  "Toyota Tacoma",
  "Chevrolet Colorado",
  "Nissan Frontier",
  "GMC Canyon",
  "Honda Ridgeline",
  "Ford F-150",
  "Chevrolet Silverado 1500",
  "Ram 1500",
  "Toyota Tundra",
  "Nissan Titan",
  "Ford Maverick",
  "Hyundai Santa Cruz",
  "Honda Passport",
  "Toyota Sequoia",
  "Nissan X-Trail",
  "Kia Telluride",
  "Hyundai Venue",
  "Toyota Venza",
  "Subaru Ascent",
  "Mitsubishi Outlander",
  "Mitsubishi Eclipse Cross",
  "Buick Enclave",
  "Cadillac XT5",
  "Cadillac XT6",
  "Lincoln Nautilus",
  "Lincoln Aviator",
  "Genesis GV70",
  "Genesis GV80",
  "Tesla Model X",
  "Tesla Model S",
  "Rivian R1T",
  "Rivian R1S",
  "Lucid Air",
  "Polestar 2",
  "Honda Odyssey",
  "Toyota Sienna",
  "Chrysler Pacifica",
  "Kia Carnival",
  "Ford Transit Connect",
  "Mercedes-Benz Metris",
  "Volkswagen ID.4",
  "Chevrolet Suburban",
  "GMC Yukon XL",
  "Toyota Land Cruiser",
  "Jeep Wrangler",
  "Jeep Gladiator",
  "Land Rover Defender",
  "Land Rover Discovery",
  "Range Rover Sport",
  "Ferrari GTC4Lusso",
  "Ferrari 599 GTB Fiorano",
  "Ferrari Enzo",
  "Lamborghini Diablo",
  "Lamborghini Countach",
  "McLaren F1",
  "McLaren 570S",
  "McLaren 650S",
  "Pagani Zonda Cinque",
  "Pagani Zonda Tricolore",
  "Koenigsegg One:1",
  "Aston Martin DB11",
  "Aston Martin AM-RB 003",
  "Lotus Evija",
  "Lotus Eletre",
  "Porsche 911 Targa 4S",
  "Porsche 911 Carrera 4",
  "Porsche 918 Spyder",
  "Maserati Levante",
  "Maserati Ghibli",
  "Bentley EXP 100 GT",
  "Audi e-tron GT",
  "Audi Q4 e-tron",
  "Mercedes EQS",
  "Mercedes EQC",
  "BMW i4",
  "BMW iX",
  "Nissan Juke",
  "Toyota MR2",
  "Honda S2000",
  "Suzuki Swift Sport",
  "Mini Cooper S",
  "Ford Puma",
  "Peugeot 208",
  "Peugeot 2008",
  "Renault Clio",
  "Alfa Romeo Giulia",
  "Alfa Romeo Stelvio",
  "Fiat 500",
  "Fiat 124 Spider",
  "Lancia Delta HF Integrale",
  "Dacia Duster",
  "Polestar 3",
  "Rimac Concept One",
  "Aptera 3",
  "Fisker Ocean",
  "De Tomaso Pantera",
  "TVR Griffith",
  "TVR Tuscan",
  "Caterham Seven",
];
