export const hexColorRegex = /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/;

export const hexColors = [
  "#FF5733",
  "#C70039",
  "#900C3F",
  "#581845",
  "#FF4500",
  "#FF6347",
  "#FF8C00",
  "#FFA500",
  "#FFD700",
  "#DAA520",
  "#B8860B",
  "#8B4513",
  "#A0522D",
  "#CD5C5C",
  "#E9967A",
  "#F08080",
  "#DC143C",
  "#8B0000",
  "#FF1493",
  "#C71585",
  "#DB7093",
  "#FF69B4",
  "#FF00FF",
  "#8A2BE2",
  "#4B0082",
  "#6A5ACD",
  "#483D8B",
  "#7B68EE",
  "#9370DB",
  "#BA55D3",
  "#9932CC",
  "#8B008B",
  "#9400D3",
  "#800080",
  "#6B8E23",
  "#556B2F",
  "#228B22",
  "#008000",
  "#006400",
  "#32CD32",
  "#00FF00",
  "#ADFF2F",
  "#7FFF00",
  "#7CFC00",
  "#00FA9A",
  "#2E8B57",
  "#3CB371",
  "#20B2AA",
  "#008B8B",
  "#008080",
  "#4682B4",
  "#1E90FF",
  "#0000CD",
  "#00008B",
  "#000080",
  "#4169E1",
  "#6495ED",
  "#00BFFF",
  "#5F9EA0",
  "#48D1CC",
  "#40E0D0",
  "#00CED1",
  "#FFD700",
  "#FFA07A",
  "#FF7F50",
  "#FF6347",
  "#FF4500",
  "#D2691E",
  "#A0522D",
  "#8B4513",
  "#CD853F",
  "#DEB887",
  "#F4A460",
  "#DAA520",
];

export const carModelsByBrand: Record<string, string[]> = {
  Acura: ["RDX", "TLX"],
  "Alfa Romeo": ["Giulia", "Stelvio"],
  Alpine: ["A110"],
  Aptera: ["3"],
  "Aston Martin": [
    "AM-RB 003",
    "DB11",
    "DBS Superleggera",
    "Rapide",
    "V12 Vantage",
    "Valkyrie",
    "Vantage",
  ],
  Audi: [
    "A4",
    "Q4 e-tron",
    "Q5",
    "Q7",
    "R8",
    "RS Q8",
    "RS5",
    "RS6 Avant",
    "RS7",
    "TT",
    "e-tron GT",
  ],
  Bentley: [
    "Bentayga",
    "Continental GT Speed",
    "EXP 100 GT",
    "Flying Spur",
    "Mulliner Bacalar",
  ],
  BMW: [
    "3 Series",
    "M2",
    "M3",
    "M4",
    "M6",
    "M8",
    "X3",
    "X5",
    "Z4",
    "i4",
    "i8",
    "iX",
  ],
  Bugatti: ["Centodieci", "Chiron", "Divo", "Veyron"],
  Buick: ["Enclave"],
  Cadillac: ["CT4", "XT5", "XT6"],
  Caterham: ["Seven"],
  Chevrolet: [
    "Blazer",
    "Bolt EV",
    "Camaro SS",
    "Colorado",
    "Corvette C8",
    "Cruze",
    "Equinox",
    "Malibu",
    "Silverado 1500",
    "Spark",
    "Suburban",
    "Tahoe",
    "Traverse",
  ],
  Chrysler: ["Pacifica"],
  Dacia: ["Duster"],
  "De Tomaso": ["Pantera"],
  Dodge: ["Challenger R/T", "Viper"],
  Ferrari: [
    "488",
    "599 GTB Fiorano",
    "812 Superfast",
    "Daytona SP3",
    "Enzo",
    "F8 Tributo",
    "GTC4Lusso",
    "Monza SP1",
    "Monza SP2",
    "Roma",
    "SF90 Stradale",
  ],
  Fiat: ["124 Spider", "500"],
  Fisker: ["Ocean"],
  Ford: [
    "Bronco",
    "Escape",
    "Expedition",
    "Explorer",
    "F-150",
    "Fiesta",
    "Focus",
    "Fusion",
    "GT",
    "Maverick",
    "Mustang GT",
    "Mustang Mach-E",
    "Puma",
    "Ranger",
    "Transit Connect",
  ],
  Genesis: ["G70", "GV70", "GV80"],
  GMC: ["Canyon", "Yukon", "Yukon XL"],
  Honda: [
    "Accord",
    "Civic",
    "CR-V",
    "Fit",
    "HR-V",
    "Insight",
    "Odyssey",
    "Passport",
    "Pilot",
    "Ridgeline",
    "S2000",
  ],
  Hyundai: [
    "Accent",
    "Elantra",
    "Ioniq",
    "Kona",
    "Palisade",
    "Santa Cruz",
    "Santa Fe",
    "Sonata",
    "Tucson",
    "Venue",
  ],
  Infiniti: ["Q50", "Q60", "QX50", "QX60"],
  Jaguar: ["E-Pace", "F-Pace", "F-Type", "XE"],
  Jeep: ["Cherokee", "Gladiator", "Grand Cherokee", "Wrangler"],
  Kia: [
    "Carnival",
    "Forte",
    "K5",
    "Niro",
    "Rio",
    "Seltos",
    "Sorento",
    "Soul",
    "Sportage",
    "Telluride",
  ],
  Koenigsegg: ["Agera RS", "Gemera", "Jesko", "One:1", "Regera"],
  Lamborghini: [
    "Aventador",
    "Centenario",
    "Countach",
    "Diablo",
    "Gallardo",
    "Huracán",
    "Murciélago",
    "Revuelto",
    "Sián",
  ],
  Lancia: ["Delta HF Integrale"],
  "Land Rover": [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Range Rover",
    "Range Rover Sport",
  ],
  Lexus: ["IS", "LC 500", "LFA", "NX", "RC F", "RX"],
  Lincoln: ["Aviator", "Nautilus"],
  Lotus: ["Elise", "Elitra", "Emira", "Evija", "Evora", "Exige"],
  Lucid: ["Air"],
  Maserati: [
    "Alfieri",
    "Ghibli",
    "GranTurismo",
    "Levante",
    "MC20",
    "Quattroporte",
  ],
  Mazda: ["CX-5", "Mazda3", "Mazda6", "MX-5 Miata"],
  McLaren: [
    "570S",
    "600LT",
    "650S",
    "720S",
    "765LT",
    "Artura",
    "Elva",
    "F1",
    "P1",
    "Senna",
  ],
  "Mercedes-Benz": [
    "AMG C63",
    "AMG GT",
    "AMG GT R",
    "AMG One",
    "AMG SL",
    "C-Class",
    "EQS",
    "EQC",
    "GLE",
    "GLC",
    "Metris",
    "SLS AMG",
  ],
  Mini: ["Cooper S"],
  Mitsubishi: ["Eclipse Cross", "Mirage", "Outlander"],
  Nissan: [
    "370Z",
    "Altima",
    "Armada",
    "Frontier",
    "GT-R",
    "Juke",
    "Leaf",
    "Murano",
    "Pathfinder",
    "Rogue",
    "Sentra",
    "Skyline GT-R",
    "Titan",
    "Versa",
    "X-Trail",
    "Z",
  ],
  Pagani: [
    "Huayra",
    "Huayra Roadster",
    "Zonda",
    "Zonda Cinque",
    "Zonda R",
    "Zonda Tricolore",
  ],
  Peugeot: ["2008", "208"],
  Polestar: ["2", "3"],
  Porsche: [
    "718 Boxster",
    "718 Cayman",
    "911 Carrera 4",
    "911 Carrera S",
    "911 GT2 RS",
    "911 GT3 RS",
    "911 Targa 4S",
    "911 Turbo S",
    "918 Spyder",
    "Cayenne",
    "Macan",
    "Panamera",
    "Taycan",
  ],
  Ram: ["1500"],
  Renault: ["Clio"],
  Rimac: ["Concept One", "Nevera"],
  Rivian: ["R1S", "R1T"],
  Subaru: ["Ascent", "BRZ", "Forester", "Impreza", "Legacy", "Outback"],
  Suzuki: ["Swift Sport"],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y"],
  Toyota: [
    "4Runner",
    "86",
    "Camry",
    "Century",
    "C-HR",
    "Corolla",
    "GR Supra",
    "Highlander",
    "Land Cruiser",
    "Prius",
    "RAV4",
    "Sequoia",
    "Sienna",
    "Tacoma",
    "Tundra",
    "Venza",
    "Yaris",
  ],
  TVR: ["Griffith", "Tuscan"],
  Volkswagen: ["Atlas", "ID.4", "Jetta", "Passat", "Tiguan"],
  Volvo: ["S60", "XC60", "XC90"],
};
